name: registapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  http: ^1.2.2
  pin_code_fields: ^8.0.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  flutter_native_splash: ^2.4.2
  flutter_facebook_auth: ^7.1.1
  firebase_database: ^11.1.4
  provider: ^6.1.2
  image_picker: ^1.1.2
  firebase_storage: ^12.3.4
  json_annotation: ^4.9.0
  url_launcher: ^6.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Tambahkan aset di bawah bagian flutter
  assets:
    - assets/tresspay.png
    - assets/s1.png
    - assets/s2.png
    - assets/s3.png
    - assets/s4.png
    - assets/s5.png
    - assets/s6.png
    - assets/avatar.jpg
